// Authentication
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAIL'
export const ON_AUTH_INPUT_CHANGE = 'ON_AUTH_INPUT_CHANGE'

export const TOGGLE_RESET_PASSWORD = 'TOGGLE_RESET_PASSWORD'
export const TOGGLE_PASSWORD_FORGOT = 'TOGGLE_PASSWORD_FORGOT'

export const TOGGLE_PASSWORD_UPDATE = 'TOGGLE_PASSWORD_UPDATE'

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'

export const EDIT_PROFILE_REQUEST = 'EDIT_PROFILE_REQUEST'
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS'
export const EDIT_PROFILE_FAIL = 'EDIT_PROFILE_FAIL'

export const RESEND_CONFIRMATION_REQUEST = 'RESEND_CONFIRMATION_REQUEST'
export const RESEND_CONFIRMATION_SUCCESS = 'RESEND_CONFIRMATION_SUCCESS'
export const RESEND_CONFIRMATION_FAIL = 'RESEND_CONFIRMATION_FAIL'

export const ON_REGISTER_INPUT_CHANGE = 'ON_REGISTER_INPUT_CHANGE'
export const ON_EDIT_INPUT_CHANGE = 'ON_EDIT_INPUT_CHANGE'

export const CONFIRM_ACCOUNT_REQUEST = 'CONFIRM_ACCOUNT_REQUEST'
export const CONFIRM_ACCOUNT_SUCCESS = 'CONFIRM_ACCOUNT_SUCCESS'
export const CONFIRM_ACCOUNT_FAIL = 'CONFIRM_ACCOUNT_FAIL'

export const LOG_OUT = 'LOG_OUT'

export const ON_FACEBOOK_LOGIN_START = 'ON_FACEBOOK_LOGIN_START'
export const ON_FACEBOOK_LOGIN_CANCEL = 'ON_FACEBOOK_LOGIN_CANCEL'
export const ON_FACEBOOK_LOGIN_FINISH = 'ON_FACEBOOK_LOGIN_FINISH'

// Venues
export const GET_VENUE_SUCCESS = 'GET_VENUE_SUCCESS'
export const GET_PREPOPULATED_VENUE = 'GET_PREPOPULATED_VENUE'
export const GET_SPORT_NAMES_SUCCESS = 'GET_SPORT_NAMES_SUCCESS'
export const SET_ACTIVE_SPORT = 'SET_ACTIVE_SPORT'
export const TOGGLE_NEW_SPORT_SELECTION = 'TOGGLE_NEW_SPORT_SELECTION'
export const GET_VENUES_BY_NAME = 'GET_VENUES_BY_NAME'

// OTHER
// Language selection
export const TOGGLE_MENU = 'TOGGLE_MENU'

// Country selection
export const ON_SELECT_COUNTRY = 'ON_SELECT_COUNTRY'

// Menus
export const TOGGLE_MOBILE_MENU = 'TOGGLE_MOBILE_MENU'
export const TOGGLE_SEARCH_MENU = 'TOGGLE_SEARCH_MENU'
export const SEARCH_BAR_CHANGE_SPORT = 'SEARCH_BAR_CHANGE_SPORT'
export const SEARCH_BAR_CHANGE_DURATION = 'SEARCH_BAR_CHANGE_DURATION'
export const SEARCH_BAR_CHANGE_DATE = 'SEARCH_BAR_CHANGE_DATE'
export const SEARCH_BAR_CHANGE_TIME = 'SEARCH_BAR_CHANGE_TIME'
export const SEARCH_BAR_CHANGE_CITY = 'SEARCH_BAR_CHANGE_CITY'

